In [15]:
import numpy as np

def generate_valid_array(rows=20, cols=5):
    array = np.random.randint(10, 101, size=(rows, cols))
    
    # Ensure each row sum is even
    for i in range(rows):
        if array[i].sum() % 2 != 0:
            array[i, 0] += 1  # Adjust the first element to make the sum even
            if array[i, 0] > 100:  # Keep values within the range
                array[i, 0] -= 2

    # Ensure total sum is a multiple of 5
    total_sum = array.sum()
    if total_sum % 5 != 0:
        adjustment = 5 - (total_sum % 5)
        array[0, 0] += adjustment
        if array[0, 0] > 100:  # Keep values within the range
            array[0, 0] -= 10

    return array

# Generate and validate the array
array = generate_valid_array()
print("Generated Array:")
print(array)

# Validation
print("\nRow Sums Even:", all(row.sum() % 2 == 0 for row in array))
print("Total Sum Multiple of 5:", array.sum() % 5 == 0)

The sum of each row is even.
The total sum of all values is a multiple of 5.

Generated Array:
[[800 460 460 210 170]
 [760 570 580 370 340]
 [300 760 980 180 840]
 [910 950 150 230 430]
 [110 110 680 530 670]
 [620 590 520 420 570]
 [910 950 160 940 260]
 [190 290 930 670 420]
 [850 160 110 360 580]
 [140 890 200 840 950]
 [650 300 460 470 510]
 [510 990 750 280 140]
 [650 220 430 930 550]
 [850 390 220 680 570]
 [260 920 770 830 990]
 [520 350 310 990 930]
 [660 940 180 750 390]
 [820 780 550 230 970]
 [450 360 830 150 290]
 [280 820 420 790 540]]


In [16]:

numbers = array[(array % 3 == 0) & (array % 5 == 0)]
print("Numbers in array which are divisible by both 3 and 5:")
print(numbers)

Numbers in array which are divisible by both 3 and 5:
[210 570 300 180 840 150 420 570 930 420 360 840 300 510 510 990 750 930
 390 570 990 990 930 660 180 750 390 780 450 360 150 420 540]


In [17]:
# Mean of the array
mean = array.mean()

for i in range(array.shape[0]):  
    for j in range(array.shape[1]):  
        # Replace elements greater than 75 with the mean
        if array[i][j] > 75:
            array[i][j] = mean

# Print the modified array
print("\nArray after replacing:")
print(array)



Array after replacing:
[[546 546 546 546 546]
 [546 546 546 546 546]
 [546 546 546 546 546]
 [546 546 546 546 546]
 [546 546 546 546 546]
 [546 546 546 546 546]
 [546 546 546 546 546]
 [546 546 546 546 546]
 [546 546 546 546 546]
 [546 546 546 546 546]
 [546 546 546 546 546]
 [546 546 546 546 546]
 [546 546 546 546 546]
 [546 546 546 546 546]
 [546 546 546 546 546]
 [546 546 546 546 546]
 [546 546 546 546 546]
 [546 546 546 546 546]
 [546 546 546 546 546]
 [546 546 546 546 546]]


In [18]:
#mean
mean = array.mean()
print("\nMean of the array:", mean)

#Standard deviation
std_deviation = array.std()
print("Standard deviation of the array:", std_deviation)

#Median
median = np.median(array)
print("Median of the array: ", median)

#Variance for each column
variance = array.var(axis=0)
print("Variance of each column:",variance)


Mean of the array: 546.0
Standard deviation of the array: 0.0
Median of the array:  546.0
Variance of each column: [0. 0. 0. 0. 0.]
